### ISSUE TITLE
Some files apparently have no parent

### ISSUE THREAD

**Issue by danog** [frogbywyplay/media_libdsmcc#1]
Hi there,
Thank you for this library, it's very useful. 
I have however encountered some problems while decoding a certain MHP object carousel with a lot of files with same names, located in different folders.

I was forced to add some additional checks in the storage module to avoid segfaults, [here](http://video.daniil.it/stream.ts) you can find an example stream that triggers this problem.

**Comment by achataignier** [comment]
Hi,

This repo contains a modified version of the original libdsmcc, modified in order to optimise RAM occupation and add a few features that we required. We may have a better chance with the original version:
https://sourceforge.net/projects/libdsmcc/
